// Code generated by cmd/generate-wrappers. DO NOT EDIT.

package client

import (
	"context"

	"github.com/DrewBradfordXYZ/quickbase-go/internal/generated"
)

// --- Auto-generated Raw wrapper methods ---
// These provide direct access to the QuickBase API matching the official documentation.
// For a fluent builder API, use the builder methods (e.g., client.CreateApp() instead of client.RawCreateApp()).
// For the underlying oapi-codegen client, use client.API().


// RawAddManagersToGroup Add managers
func (c *Client) RawAddManagersToGroup(ctx context.Context, gid float32, body generated.AddManagersToGroupJSONRequestBody) (*generated.AddManagersToGroupResponse, error) {
	resp, err := c.API().AddManagersToGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawAddMembersToGroup Add members
func (c *Client) RawAddMembersToGroup(ctx context.Context, gid float32, body generated.AddMembersToGroupJSONRequestBody) (*generated.AddMembersToGroupResponse, error) {
	resp, err := c.API().AddMembersToGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawAddSubgroupsToGroup Add child groups
func (c *Client) RawAddSubgroupsToGroup(ctx context.Context, gid float32, body generated.AddSubgroupsToGroupJSONRequestBody) (*generated.AddSubgroupsToGroupResponse, error) {
	resp, err := c.API().AddSubgroupsToGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawAudit Get audit logs
func (c *Client) RawAudit(ctx context.Context, body generated.AuditJSONRequestBody) (*generated.AuditResponse, error) {
	resp, err := c.API().AuditWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawChangesetSolution List solution changes
func (c *Client) RawChangesetSolution(ctx context.Context, solutionId string, params *generated.ChangesetSolutionParams, body generated.ChangesetSolutionJSONRequestBody) (*generated.ChangesetSolutionResponse, error) {
	resp, err := c.API().ChangesetSolutionWithResponse(ctx, solutionId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawChangesetSolutionFromRecord List solution changes from record
func (c *Client) RawChangesetSolutionFromRecord(ctx context.Context, solutionId string, params *generated.ChangesetSolutionFromRecordParams) (*generated.ChangesetSolutionFromRecordResponse, error) {
	resp, err := c.API().ChangesetSolutionFromRecordWithResponse(ctx, solutionId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawCloneUserToken Clone a user token
func (c *Client) RawCloneUserToken(ctx context.Context, body generated.CloneUserTokenJSONRequestBody) (*generated.CloneUserTokenResponse, error) {
	resp, err := c.API().CloneUserTokenWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawCopyApp Copy an app
func (c *Client) RawCopyApp(ctx context.Context, appId string, body generated.CopyAppJSONRequestBody) (*generated.CopyAppResponse, error) {
	resp, err := c.API().CopyAppWithResponse(ctx, appId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawCreateApp Create an app
func (c *Client) RawCreateApp(ctx context.Context, body generated.CreateAppJSONRequestBody) (*generated.CreateAppResponse, error) {
	resp, err := c.API().CreateAppWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawCreateField Create a field
func (c *Client) RawCreateField(ctx context.Context, params *generated.CreateFieldParams, body generated.CreateFieldJSONRequestBody) (*generated.CreateFieldResponse, error) {
	resp, err := c.API().CreateFieldWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawCreateRelationship Create a relationship
func (c *Client) RawCreateRelationship(ctx context.Context, tableId string, body generated.CreateRelationshipJSONRequestBody) (*generated.CreateRelationshipResponse, error) {
	resp, err := c.API().CreateRelationshipWithResponse(ctx, tableId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawCreateSolution Create a solution
func (c *Client) RawCreateSolution(ctx context.Context, params *generated.CreateSolutionParams, body generated.CreateSolutionJSONRequestBody) (*generated.CreateSolutionResponse, error) {
	resp, err := c.API().CreateSolutionWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawCreateSolutionFromRecord Create solution from record
func (c *Client) RawCreateSolutionFromRecord(ctx context.Context, params *generated.CreateSolutionFromRecordParams) (*generated.CreateSolutionFromRecordResponse, error) {
	resp, err := c.API().CreateSolutionFromRecordWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawCreateTable Create a table
func (c *Client) RawCreateTable(ctx context.Context, params *generated.CreateTableParams, body generated.CreateTableJSONRequestBody) (*generated.CreateTableResponse, error) {
	resp, err := c.API().CreateTableWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDeactivateUserToken Deactivate a user token
func (c *Client) RawDeactivateUserToken(ctx context.Context) (*generated.DeactivateUserTokenResponse, error) {
	resp, err := c.API().DeactivateUserTokenWithResponse(ctx)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDeleteApp Delete an app
func (c *Client) RawDeleteApp(ctx context.Context, appId string, body generated.DeleteAppJSONRequestBody) (*generated.DeleteAppResponse, error) {
	resp, err := c.API().DeleteAppWithResponse(ctx, appId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDeleteFields Delete field(s)
func (c *Client) RawDeleteFields(ctx context.Context, params *generated.DeleteFieldsParams, body generated.DeleteFieldsJSONRequestBody) (*generated.DeleteFieldsResponse, error) {
	resp, err := c.API().DeleteFieldsWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDeleteFile Delete file
func (c *Client) RawDeleteFile(ctx context.Context, tableId string, recordId int, fieldId int, versionNumber int) (*generated.DeleteFileResponse, error) {
	resp, err := c.API().DeleteFileWithResponse(ctx, tableId, recordId, fieldId, versionNumber)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDeleteRelationship Delete a relationship
func (c *Client) RawDeleteRelationship(ctx context.Context, tableId string, relationshipId float32) (*generated.DeleteRelationshipResponse, error) {
	resp, err := c.API().DeleteRelationshipWithResponse(ctx, tableId, relationshipId)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDeleteTable Delete a table
func (c *Client) RawDeleteTable(ctx context.Context, tableId string, params *generated.DeleteTableParams) (*generated.DeleteTableResponse, error) {
	resp, err := c.API().DeleteTableWithResponse(ctx, tableId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDeleteUserToken Delete a user token
func (c *Client) RawDeleteUserToken(ctx context.Context) (*generated.DeleteUserTokenResponse, error) {
	resp, err := c.API().DeleteUserTokenWithResponse(ctx)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDenyUsers Deny users
func (c *Client) RawDenyUsers(ctx context.Context, params *generated.DenyUsersParams, body generated.DenyUsersJSONRequestBody) (*generated.DenyUsersResponse, error) {
	resp, err := c.API().DenyUsersWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDenyUsersAndGroups Deny and remove users from groups
func (c *Client) RawDenyUsersAndGroups(ctx context.Context, shouldDeleteFromGroups bool, params *generated.DenyUsersAndGroupsParams, body generated.DenyUsersAndGroupsJSONRequestBody) (*generated.DenyUsersAndGroupsResponse, error) {
	resp, err := c.API().DenyUsersAndGroupsWithResponse(ctx, shouldDeleteFromGroups, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawDownloadFile Download file
func (c *Client) RawDownloadFile(ctx context.Context, tableId string, recordId int, fieldId int, versionNumber int) (*generated.DownloadFileResponse, error) {
	resp, err := c.API().DownloadFileWithResponse(ctx, tableId, recordId, fieldId, versionNumber)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawExchangeSsoToken Exchange an SSO token
func (c *Client) RawExchangeSsoToken(ctx context.Context, body generated.ExchangeSsoTokenJSONRequestBody) (*generated.ExchangeSsoTokenResponse, error) {
	resp, err := c.API().ExchangeSsoTokenWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawExportSolution Export a solution
func (c *Client) RawExportSolution(ctx context.Context, solutionId string, params *generated.ExportSolutionParams) (*generated.ExportSolutionResponse, error) {
	resp, err := c.API().ExportSolutionWithResponse(ctx, solutionId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawExportSolutionToRecord Export solution to record
func (c *Client) RawExportSolutionToRecord(ctx context.Context, solutionId string, params *generated.ExportSolutionToRecordParams) (*generated.ExportSolutionToRecordResponse, error) {
	resp, err := c.API().ExportSolutionToRecordWithResponse(ctx, solutionId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGenerateDocument Generate a document
func (c *Client) RawGenerateDocument(ctx context.Context, templateId float32, params *generated.GenerateDocumentParams) (*generated.GenerateDocumentResponse, error) {
	resp, err := c.API().GenerateDocumentWithResponse(ctx, templateId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetAppEvents Get app events
func (c *Client) RawGetAppEvents(ctx context.Context, appId string) (*generated.GetAppEventsResponse, error) {
	resp, err := c.API().GetAppEventsWithResponse(ctx, appId)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetAppTables Get tables for an app
func (c *Client) RawGetAppTables(ctx context.Context, params *generated.GetAppTablesParams) (*generated.GetAppTablesResponse, error) {
	resp, err := c.API().GetAppTablesWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetField Get field
func (c *Client) RawGetField(ctx context.Context, fieldId int, params *generated.GetFieldParams) (*generated.GetFieldResponse, error) {
	resp, err := c.API().GetFieldWithResponse(ctx, fieldId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetFieldUsage Get usage for a field
func (c *Client) RawGetFieldUsage(ctx context.Context, fieldId int, params *generated.GetFieldUsageParams) (*generated.GetFieldUsageResponse, error) {
	resp, err := c.API().GetFieldUsageWithResponse(ctx, fieldId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetFieldsUsage Get usage for all fields
func (c *Client) RawGetFieldsUsage(ctx context.Context, params *generated.GetFieldsUsageParams) (*generated.GetFieldsUsageResponse, error) {
	resp, err := c.API().GetFieldsUsageWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetRelationships Get all relationships
func (c *Client) RawGetRelationships(ctx context.Context, tableId string, params *generated.GetRelationshipsParams) (*generated.GetRelationshipsResponse, error) {
	resp, err := c.API().GetRelationshipsWithResponse(ctx, tableId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetReport Get a report
func (c *Client) RawGetReport(ctx context.Context, reportId string, params *generated.GetReportParams) (*generated.GetReportResponse, error) {
	resp, err := c.API().GetReportWithResponse(ctx, reportId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetTable Get a table
func (c *Client) RawGetTable(ctx context.Context, tableId string, params *generated.GetTableParams) (*generated.GetTableResponse, error) {
	resp, err := c.API().GetTableWithResponse(ctx, tableId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetTableReports Get reports for a table
func (c *Client) RawGetTableReports(ctx context.Context, params *generated.GetTableReportsParams) (*generated.GetTableReportsResponse, error) {
	resp, err := c.API().GetTableReportsWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetTempTokenDBID Get a temporary token for a dbid
func (c *Client) RawGetTempTokenDBID(ctx context.Context, dbid string, params *generated.GetTempTokenDBIDParams) (*generated.GetTempTokenDBIDResponse, error) {
	resp, err := c.API().GetTempTokenDBIDWithResponse(ctx, dbid, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawGetUsers Get users
func (c *Client) RawGetUsers(ctx context.Context, params *generated.GetUsersParams, body generated.GetUsersJSONRequestBody) (*generated.GetUsersResponse, error) {
	resp, err := c.API().GetUsersWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawPlatformAnalyticEventSummaries Get event summaries
func (c *Client) RawPlatformAnalyticEventSummaries(ctx context.Context, params *generated.PlatformAnalyticEventSummariesParams, body generated.PlatformAnalyticEventSummariesJSONRequestBody) (*generated.PlatformAnalyticEventSummariesResponse, error) {
	resp, err := c.API().PlatformAnalyticEventSummariesWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawPlatformAnalyticReads Get read summaries
func (c *Client) RawPlatformAnalyticReads(ctx context.Context, params *generated.PlatformAnalyticReadsParams) (*generated.PlatformAnalyticReadsResponse, error) {
	resp, err := c.API().PlatformAnalyticReadsWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawRemoveManagersFromGroup Remove managers
func (c *Client) RawRemoveManagersFromGroup(ctx context.Context, gid float32, body generated.RemoveManagersFromGroupJSONRequestBody) (*generated.RemoveManagersFromGroupResponse, error) {
	resp, err := c.API().RemoveManagersFromGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawRemoveMembersFromGroup Remove members
func (c *Client) RawRemoveMembersFromGroup(ctx context.Context, gid float32, body generated.RemoveMembersFromGroupJSONRequestBody) (*generated.RemoveMembersFromGroupResponse, error) {
	resp, err := c.API().RemoveMembersFromGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawRemoveSubgroupsFromGroup Remove child groups
func (c *Client) RawRemoveSubgroupsFromGroup(ctx context.Context, gid float32, body generated.RemoveSubgroupsFromGroupJSONRequestBody) (*generated.RemoveSubgroupsFromGroupResponse, error) {
	resp, err := c.API().RemoveSubgroupsFromGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawRunFormula Run a formula
func (c *Client) RawRunFormula(ctx context.Context, body generated.RunFormulaJSONRequestBody) (*generated.RunFormulaResponse, error) {
	resp, err := c.API().RunFormulaWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawRunReport Run a report
func (c *Client) RawRunReport(ctx context.Context, reportId string, params *generated.RunReportParams, body generated.RunReportJSONRequestBody) (*generated.RunReportResponse, error) {
	resp, err := c.API().RunReportWithResponse(ctx, reportId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawTransferUserToken Transfer a user token
func (c *Client) RawTransferUserToken(ctx context.Context, body generated.TransferUserTokenJSONRequestBody) (*generated.TransferUserTokenResponse, error) {
	resp, err := c.API().TransferUserTokenWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawUndenyUsers Undeny users
func (c *Client) RawUndenyUsers(ctx context.Context, params *generated.UndenyUsersParams, body generated.UndenyUsersJSONRequestBody) (*generated.UndenyUsersResponse, error) {
	resp, err := c.API().UndenyUsersWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawUpdateApp Update an app
func (c *Client) RawUpdateApp(ctx context.Context, appId string, body generated.UpdateAppJSONRequestBody) (*generated.UpdateAppResponse, error) {
	resp, err := c.API().UpdateAppWithResponse(ctx, appId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawUpdateField Update a field
func (c *Client) RawUpdateField(ctx context.Context, fieldId int, params *generated.UpdateFieldParams, body generated.UpdateFieldJSONRequestBody) (*generated.UpdateFieldResponse, error) {
	resp, err := c.API().UpdateFieldWithResponse(ctx, fieldId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawUpdateRelationship Update a relationship
func (c *Client) RawUpdateRelationship(ctx context.Context, tableId string, relationshipId float32, body generated.UpdateRelationshipJSONRequestBody) (*generated.UpdateRelationshipResponse, error) {
	resp, err := c.API().UpdateRelationshipWithResponse(ctx, tableId, relationshipId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawUpdateSolution Update a solution
func (c *Client) RawUpdateSolution(ctx context.Context, solutionId string, params *generated.UpdateSolutionParams, body generated.UpdateSolutionJSONRequestBody) (*generated.UpdateSolutionResponse, error) {
	resp, err := c.API().UpdateSolutionWithResponse(ctx, solutionId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawUpdateSolutionToRecord Update solution from record
func (c *Client) RawUpdateSolutionToRecord(ctx context.Context, solutionId string, params *generated.UpdateSolutionToRecordParams) (*generated.UpdateSolutionToRecordResponse, error) {
	resp, err := c.API().UpdateSolutionToRecordWithResponse(ctx, solutionId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RawUpdateTable Update a table
func (c *Client) RawUpdateTable(ctx context.Context, tableId string, params *generated.UpdateTableParams, body generated.UpdateTableJSONRequestBody) (*generated.UpdateTableResponse, error) {
	resp, err := c.API().UpdateTableWithResponse(ctx, tableId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

