// Code generated by cmd/generate-wrappers. DO NOT EDIT.

package client

import (
	"context"

	"github.com/DrewBradfordXYZ/quickbase-go/internal/generated"
)

// --- Auto-generated wrapper methods ---
// These provide a cleaner API over the generated oapi-codegen client.
// For full control, use client.API() to access the underlying client.


// AddManagersToGroup Add managers
func (c *Client) AddManagersToGroup(ctx context.Context, gid float32, body generated.AddManagersToGroupJSONRequestBody) (*generated.AddManagersToGroupResponse, error) {
	resp, err := c.API().AddManagersToGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// AddMembersToGroup Add members
func (c *Client) AddMembersToGroup(ctx context.Context, gid float32, body generated.AddMembersToGroupJSONRequestBody) (*generated.AddMembersToGroupResponse, error) {
	resp, err := c.API().AddMembersToGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// AddSubgroupsToGroup Add child groups
func (c *Client) AddSubgroupsToGroup(ctx context.Context, gid float32, body generated.AddSubgroupsToGroupJSONRequestBody) (*generated.AddSubgroupsToGroupResponse, error) {
	resp, err := c.API().AddSubgroupsToGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// Audit Get audit logs
func (c *Client) Audit(ctx context.Context, body generated.AuditJSONRequestBody) (*generated.AuditResponse, error) {
	resp, err := c.API().AuditWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// ChangesetSolution List solution changes
func (c *Client) ChangesetSolution(ctx context.Context, solutionId string, params *generated.ChangesetSolutionParams, body generated.ChangesetSolutionJSONRequestBody) (*generated.ChangesetSolutionResponse, error) {
	resp, err := c.API().ChangesetSolutionWithResponse(ctx, solutionId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// ChangesetSolutionFromRecord List solution changes from record
func (c *Client) ChangesetSolutionFromRecord(ctx context.Context, solutionId string, params *generated.ChangesetSolutionFromRecordParams) (*generated.ChangesetSolutionFromRecordResponse, error) {
	resp, err := c.API().ChangesetSolutionFromRecordWithResponse(ctx, solutionId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// CloneUserToken Clone a user token
func (c *Client) CloneUserToken(ctx context.Context, body generated.CloneUserTokenJSONRequestBody) (*generated.CloneUserTokenResponse, error) {
	resp, err := c.API().CloneUserTokenWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// CopyApp Copy an app
func (c *Client) CopyApp(ctx context.Context, appId string, body generated.CopyAppJSONRequestBody) (*generated.CopyAppResponse, error) {
	resp, err := c.API().CopyAppWithResponse(ctx, appId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// CreateApp Create an app
func (c *Client) CreateApp(ctx context.Context, body generated.CreateAppJSONRequestBody) (*generated.CreateAppResponse, error) {
	resp, err := c.API().CreateAppWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// CreateField Create a field
func (c *Client) CreateField(ctx context.Context, params *generated.CreateFieldParams, body generated.CreateFieldJSONRequestBody) (*generated.CreateFieldResponse, error) {
	resp, err := c.API().CreateFieldWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// CreateRelationship Create a relationship
func (c *Client) CreateRelationship(ctx context.Context, tableId string, body generated.CreateRelationshipJSONRequestBody) (*generated.CreateRelationshipResponse, error) {
	resp, err := c.API().CreateRelationshipWithResponse(ctx, tableId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// CreateSolution Create a solution
func (c *Client) CreateSolution(ctx context.Context, params *generated.CreateSolutionParams, body generated.CreateSolutionJSONRequestBody) (*generated.CreateSolutionResponse, error) {
	resp, err := c.API().CreateSolutionWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// CreateSolutionFromRecord Create solution from record
func (c *Client) CreateSolutionFromRecord(ctx context.Context, params *generated.CreateSolutionFromRecordParams) (*generated.CreateSolutionFromRecordResponse, error) {
	resp, err := c.API().CreateSolutionFromRecordWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// CreateTable Create a table
func (c *Client) CreateTable(ctx context.Context, params *generated.CreateTableParams, body generated.CreateTableJSONRequestBody) (*generated.CreateTableResponse, error) {
	resp, err := c.API().CreateTableWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DeactivateUserToken Deactivate a user token
func (c *Client) DeactivateUserToken(ctx context.Context) (*generated.DeactivateUserTokenResponse, error) {
	resp, err := c.API().DeactivateUserTokenWithResponse(ctx)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DeleteApp Delete an app
func (c *Client) DeleteApp(ctx context.Context, appId string, body generated.DeleteAppJSONRequestBody) (*generated.DeleteAppResponse, error) {
	resp, err := c.API().DeleteAppWithResponse(ctx, appId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DeleteFields Delete field(s)
func (c *Client) DeleteFields(ctx context.Context, params *generated.DeleteFieldsParams, body generated.DeleteFieldsJSONRequestBody) (*generated.DeleteFieldsResponse, error) {
	resp, err := c.API().DeleteFieldsWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DeleteFile Delete file
func (c *Client) DeleteFile(ctx context.Context, tableId string, recordId int, fieldId int, versionNumber int) (*generated.DeleteFileResponse, error) {
	resp, err := c.API().DeleteFileWithResponse(ctx, tableId, recordId, fieldId, versionNumber)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DeleteRelationship Delete a relationship
func (c *Client) DeleteRelationship(ctx context.Context, tableId string, relationshipId float32) (*generated.DeleteRelationshipResponse, error) {
	resp, err := c.API().DeleteRelationshipWithResponse(ctx, tableId, relationshipId)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DeleteTable Delete a table
func (c *Client) DeleteTable(ctx context.Context, tableId string, params *generated.DeleteTableParams) (*generated.DeleteTableResponse, error) {
	resp, err := c.API().DeleteTableWithResponse(ctx, tableId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DeleteUserToken Delete a user token
func (c *Client) DeleteUserToken(ctx context.Context) (*generated.DeleteUserTokenResponse, error) {
	resp, err := c.API().DeleteUserTokenWithResponse(ctx)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DenyUsers Deny users
func (c *Client) DenyUsers(ctx context.Context, params *generated.DenyUsersParams, body generated.DenyUsersJSONRequestBody) (*generated.DenyUsersResponse, error) {
	resp, err := c.API().DenyUsersWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DenyUsersAndGroups Deny and remove users from groups
func (c *Client) DenyUsersAndGroups(ctx context.Context, shouldDeleteFromGroups bool, params *generated.DenyUsersAndGroupsParams, body generated.DenyUsersAndGroupsJSONRequestBody) (*generated.DenyUsersAndGroupsResponse, error) {
	resp, err := c.API().DenyUsersAndGroupsWithResponse(ctx, shouldDeleteFromGroups, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// DownloadFile Download file
func (c *Client) DownloadFile(ctx context.Context, tableId string, recordId int, fieldId int, versionNumber int) (*generated.DownloadFileResponse, error) {
	resp, err := c.API().DownloadFileWithResponse(ctx, tableId, recordId, fieldId, versionNumber)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// ExchangeSsoToken Exchange an SSO token
func (c *Client) ExchangeSsoToken(ctx context.Context, body generated.ExchangeSsoTokenJSONRequestBody) (*generated.ExchangeSsoTokenResponse, error) {
	resp, err := c.API().ExchangeSsoTokenWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// ExportSolution Export a solution
func (c *Client) ExportSolution(ctx context.Context, solutionId string, params *generated.ExportSolutionParams) (*generated.ExportSolutionResponse, error) {
	resp, err := c.API().ExportSolutionWithResponse(ctx, solutionId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// ExportSolutionToRecord Export solution to record
func (c *Client) ExportSolutionToRecord(ctx context.Context, solutionId string, params *generated.ExportSolutionToRecordParams) (*generated.ExportSolutionToRecordResponse, error) {
	resp, err := c.API().ExportSolutionToRecordWithResponse(ctx, solutionId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GenerateDocument Generate a document
func (c *Client) GenerateDocument(ctx context.Context, templateId float32, params *generated.GenerateDocumentParams) (*generated.GenerateDocumentResponse, error) {
	resp, err := c.API().GenerateDocumentWithResponse(ctx, templateId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetAppEvents Get app events
func (c *Client) GetAppEvents(ctx context.Context, appId string) (*generated.GetAppEventsResponse, error) {
	resp, err := c.API().GetAppEventsWithResponse(ctx, appId)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetAppTables Get tables for an app
func (c *Client) GetAppTables(ctx context.Context, params *generated.GetAppTablesParams) (*generated.GetAppTablesResponse, error) {
	resp, err := c.API().GetAppTablesWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetField Get field
func (c *Client) GetField(ctx context.Context, fieldId int, params *generated.GetFieldParams) (*generated.GetFieldResponse, error) {
	resp, err := c.API().GetFieldWithResponse(ctx, fieldId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetFieldUsage Get usage for a field
func (c *Client) GetFieldUsage(ctx context.Context, fieldId int, params *generated.GetFieldUsageParams) (*generated.GetFieldUsageResponse, error) {
	resp, err := c.API().GetFieldUsageWithResponse(ctx, fieldId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetFieldsUsage Get usage for all fields
func (c *Client) GetFieldsUsage(ctx context.Context, params *generated.GetFieldsUsageParams) (*generated.GetFieldsUsageResponse, error) {
	resp, err := c.API().GetFieldsUsageWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetRelationships Get all relationships
func (c *Client) GetRelationships(ctx context.Context, tableId string, params *generated.GetRelationshipsParams) (*generated.GetRelationshipsResponse, error) {
	resp, err := c.API().GetRelationshipsWithResponse(ctx, tableId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetReport Get a report
func (c *Client) GetReport(ctx context.Context, reportId string, params *generated.GetReportParams) (*generated.GetReportResponse, error) {
	resp, err := c.API().GetReportWithResponse(ctx, reportId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetTable Get a table
func (c *Client) GetTable(ctx context.Context, tableId string, params *generated.GetTableParams) (*generated.GetTableResponse, error) {
	resp, err := c.API().GetTableWithResponse(ctx, tableId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetTableReports Get reports for a table
func (c *Client) GetTableReports(ctx context.Context, params *generated.GetTableReportsParams) (*generated.GetTableReportsResponse, error) {
	resp, err := c.API().GetTableReportsWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetTempTokenDBID Get a temporary token for a dbid
func (c *Client) GetTempTokenDBID(ctx context.Context, dbid string, params *generated.GetTempTokenDBIDParams) (*generated.GetTempTokenDBIDResponse, error) {
	resp, err := c.API().GetTempTokenDBIDWithResponse(ctx, dbid, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// GetUsers Get users
func (c *Client) GetUsers(ctx context.Context, params *generated.GetUsersParams, body generated.GetUsersJSONRequestBody) (*generated.GetUsersResponse, error) {
	resp, err := c.API().GetUsersWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// PlatformAnalyticEventSummaries Get event summaries
func (c *Client) PlatformAnalyticEventSummaries(ctx context.Context, params *generated.PlatformAnalyticEventSummariesParams, body generated.PlatformAnalyticEventSummariesJSONRequestBody) (*generated.PlatformAnalyticEventSummariesResponse, error) {
	resp, err := c.API().PlatformAnalyticEventSummariesWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// PlatformAnalyticReads Get read summaries
func (c *Client) PlatformAnalyticReads(ctx context.Context, params *generated.PlatformAnalyticReadsParams) (*generated.PlatformAnalyticReadsResponse, error) {
	resp, err := c.API().PlatformAnalyticReadsWithResponse(ctx, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RemoveManagersFromGroup Remove managers
func (c *Client) RemoveManagersFromGroup(ctx context.Context, gid float32, body generated.RemoveManagersFromGroupJSONRequestBody) (*generated.RemoveManagersFromGroupResponse, error) {
	resp, err := c.API().RemoveManagersFromGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RemoveMembersFromGroup Remove members
func (c *Client) RemoveMembersFromGroup(ctx context.Context, gid float32, body generated.RemoveMembersFromGroupJSONRequestBody) (*generated.RemoveMembersFromGroupResponse, error) {
	resp, err := c.API().RemoveMembersFromGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RemoveSubgroupsFromGroup Remove child groups
func (c *Client) RemoveSubgroupsFromGroup(ctx context.Context, gid float32, body generated.RemoveSubgroupsFromGroupJSONRequestBody) (*generated.RemoveSubgroupsFromGroupResponse, error) {
	resp, err := c.API().RemoveSubgroupsFromGroupWithResponse(ctx, gid, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RunFormula Run a formula
func (c *Client) RunFormula(ctx context.Context, body generated.RunFormulaJSONRequestBody) (*generated.RunFormulaResponse, error) {
	resp, err := c.API().RunFormulaWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// RunReport Run a report
func (c *Client) RunReport(ctx context.Context, reportId string, params *generated.RunReportParams, body generated.RunReportJSONRequestBody) (*generated.RunReportResponse, error) {
	resp, err := c.API().RunReportWithResponse(ctx, reportId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// TransferUserToken Transfer a user token
func (c *Client) TransferUserToken(ctx context.Context, body generated.TransferUserTokenJSONRequestBody) (*generated.TransferUserTokenResponse, error) {
	resp, err := c.API().TransferUserTokenWithResponse(ctx, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// UndenyUsers Undeny users
func (c *Client) UndenyUsers(ctx context.Context, params *generated.UndenyUsersParams, body generated.UndenyUsersJSONRequestBody) (*generated.UndenyUsersResponse, error) {
	resp, err := c.API().UndenyUsersWithResponse(ctx, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// UpdateApp Update an app
func (c *Client) UpdateApp(ctx context.Context, appId string, body generated.UpdateAppJSONRequestBody) (*generated.UpdateAppResponse, error) {
	resp, err := c.API().UpdateAppWithResponse(ctx, appId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// UpdateField Update a field
func (c *Client) UpdateField(ctx context.Context, fieldId int, params *generated.UpdateFieldParams, body generated.UpdateFieldJSONRequestBody) (*generated.UpdateFieldResponse, error) {
	resp, err := c.API().UpdateFieldWithResponse(ctx, fieldId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// UpdateRelationship Update a relationship
func (c *Client) UpdateRelationship(ctx context.Context, tableId string, relationshipId float32, body generated.UpdateRelationshipJSONRequestBody) (*generated.UpdateRelationshipResponse, error) {
	resp, err := c.API().UpdateRelationshipWithResponse(ctx, tableId, relationshipId, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// UpdateSolution Update a solution
func (c *Client) UpdateSolution(ctx context.Context, solutionId string, params *generated.UpdateSolutionParams, body generated.UpdateSolutionJSONRequestBody) (*generated.UpdateSolutionResponse, error) {
	resp, err := c.API().UpdateSolutionWithResponse(ctx, solutionId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// UpdateSolutionToRecord Update solution from record
func (c *Client) UpdateSolutionToRecord(ctx context.Context, solutionId string, params *generated.UpdateSolutionToRecordParams) (*generated.UpdateSolutionToRecordResponse, error) {
	resp, err := c.API().UpdateSolutionToRecordWithResponse(ctx, solutionId, params)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

// UpdateTable Update a table
func (c *Client) UpdateTable(ctx context.Context, tableId string, params *generated.UpdateTableParams, body generated.UpdateTableJSONRequestBody) (*generated.UpdateTableResponse, error) {
	resp, err := c.API().UpdateTableWithResponse(ctx, tableId, params, body)
	if err != nil {
		return nil, err
	}
	if resp.JSON200 == nil {
		return nil, parseAPIError(resp.StatusCode(), resp.Body, resp.HTTPResponse)
	}
	return resp, nil
}

